Update Error Nooralyzer
for (Analyzing Tuya Devices error logs...) if there are results, I put that along with the results (Link case to PT 4270818).  And for (Analyzing 'nl_recvmsgs failed: -5' errors...) if there are results, i put that along with the results (Link to PT 4935316 )

diff --git a/Error Nooralyzer b/Error Nooralyzer
--- a/Error Nooralyzer
+++ b/Error Nooralyzer
@@ -3,14 +3,15 @@
 # Function to display the design
 display_design() {
     cat << "EOF"
-                              )                                               
-                           ( /(                       (                       
- (    (    (         (     )\())           (       )  )\ (           (   (    
- )\   )(   )(    (   )(   ((_)\   (    (   )(   ( /( ((_))\ )  (    ))\  )(   
-((_) (()\ (()\   )\ (()\   _((_)  )\   )\ (()\  )(_)) _ (()/(  )\  /((_)(()\  
-| __| ((_) ((_) ((_) ((_) | \| | ((_) ((_) ((_)((_)_ | | )(_))((_)(_))   ((_) 
-| _| | '_|| '_|/ _ \| '_| | .` |/ _ \/ _ \| '_|/ _` || || || ||_ // -_) | '_| 
-|___||_|  |_|  \___/|_|   |_|\_|\___/\___/|_|  \__,_||_| \_, |/__|\___| |_|          
+
+  ______                           _   _                            _                        
+ |  ____|                         | \ | |                          | |                       
+ | |__    _ __  _ __  ___   _ __  |  \| |  ___    ___   _ __  __ _ | | _   _  ____ ___  _ __ 
+ |  __|  | '__|| '__|/ _ \ | '__| | . ` | / _ \  / _ \ | '__|/ _` || || | | ||_  // _ \| '__|
+ | |____ | |   | |  | (_) || |    | |\  || (_) || (_) || |  | (_| || || |_| | / /|  __/| |   
+ |______||_|   |_|   \___/ |_|    |_| \_| \___/  \___/ |_|   \__,_||_| \__, |/___|\___||_|   
+                                                                        __/ |                
+                                                                       |___/                           
 By Noor Shaheed, Datto, Kaseya. 01/10/2024
 Error Log Analyzer
 ----------------------------
@@ -26,14 +27,21 @@ analyze_tuya_errors() {
         echo "No Tuya devices detected."
     else
         echo "$tuya_logs"
+        echo "Link to PT 4270818"
     fi
 }
 
 # Function to analyze "nl_recvmsgs failed: -5" errors
 analyze_nl_recvmsgs_errors() {
     echo "Analyzing 'nl_recvmsgs failed: -5' errors..."
-    logread | grep -i recvmsgs
-    grep -i "did not acknowledge authentication response\|wpa_driver_nl80211_event_receive->nl_recvmsgs failed -5" /var/log/messages*
+    nl_recvmsgs_logs=$(grep -i recvmsgs /var/log/messages*)
+    
+    if [ -z "$nl_recvmsgs_logs" ]; then
+        echo "No nl_recvmsgs failed: -5 errors detected."
+    else
+        echo "$nl_recvmsgs_logs"
+        echo "Link to PT 4935316"
+    fi
 }
 
 # Main function
